"""empty message

Revision ID: 943266722cd6
Revises: e12429209919
Create Date: 2020-02-25 14:05:01.936045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943266722cd6'
down_revision = 'e12429209919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_service_number', table_name='employees')
    op.create_index(op.f('ix_employees_service_number'), 'employees', ['service_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_service_number'), table_name='employees')
    op.create_index('ix_employees_service_number', 'employees', ['service_number'], unique=False)
    # ### end Alembic commands ###
