"""empty message

Revision ID: b36ee3091d4a
Revises: dd9b19baa62c
Create Date: 2020-03-10 12:08:14.103505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36ee3091d4a'
down_revision = 'dd9b19baa62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_shift', sa.Column('marked_department', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_shift', 'marked_department')
    # ### end Alembic commands ###
