"""empty message

Revision ID: e12429209919
Revises: 54799a04d08a
Create Date: 2020-02-25 13:06:29.971324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12429209919'
down_revision = '54799a04d08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_service_number', table_name='employees')
    op.create_index(op.f('ix_employees_service_number'), 'employees', ['service_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_service_number'), table_name='employees')
    op.create_index('ix_employees_service_number', 'employees', ['service_number'], unique=1)
    # ### end Alembic commands ###
